version: '3.8'

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    command: "-jar DynamoDBLocal.jar sharedDb -dbPath ./data"
    working_dir: /home/dynamodblocal
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    ports:
      - "8000:8000"

  user-management-service:
    image: ghcr.io/samirmarin/user-management-service-cicd:test-tag
    container_name: user-management-service
    ports:
      - "1324:1324"
    environment:
      - AWS_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DYNAMODB_LOCAL_ENDPOINT=http://dynamodb-local:8000
    depends_on:
      - dynamodb-local